model = "{{ default .Codex.Model "gpt-5.3-codex" }}"
model_reasoning_effort = "{{ default .Codex.ModelReasoningEffort "medium" }}"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_verbosity = "low"
web_search_request = true
